Spot It Free/Proyecto Spot-it Free/Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class ArtistasController : Controller
    {
        private espotiEntities db = new espotiEntities();

        // GET: Artistas
        public async Task<ActionResult> Index()
        {
            
            var artista = db.Artista.Include(a => a.Usuario1);
            return View(await artista.ToListAsync());
        }

        // GET: Artistas/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // GET: Artistas/Create
        public ActionResult Create()
        {
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre");
            return View();
        }

        // POST: Artistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Usuario,Nombre_artista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Artista.Add(artista);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // GET: Artistas/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // POST: Artistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Usuario,Nombre_artista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artista).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // GET: Artistas/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Artista artista = await db.Artista.FindAsync(id);

            List<Disco> c = new List<Disco>();
            c = artista.Disco.ToList<Disco>();

            for (int i = 0; i < c.Count; i++)
            {
                db.Disco.Remove(c[i]);
                await db.SaveChangesAsync();
            }

            db.Artista.Remove(artista);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Spot It Free/Proyecto Spot-it Free/Controllers/ExploraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free.Models;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class ExploraController : Controller
    {
        private espotiEntities db = new espotiEntities();

        // GET: Explora
        public ActionResult Index(string localidad)
        {
            Explora e = new Explora(localidad);

            List<Cancion> k = new List<Cancion>();
            List<Disco> dk = new List<Disco>();
            List<Artista> at = new List<Artista>();
            List<Artista> local = new List<Artista>();

            Trace.TraceInformation(":::::::::::::::localidad:::::::::::::::"+localidad);


            for (int i = 0; i<e.CancionesID.Count();i++) {
                int id = e.CancionesID[i];
                Cancion cs = db.Cancion.Where(x => x.Id == id).SingleOrDefault(); 
                k.Add(cs);
            }
            for (int i = 0; i < e.DiscosID.Count(); i++)
            {
                int id = e.DiscosID[i];
                var disco = db.Disco.Where(x => x.Id == id).FirstOrDefault();
                dk.Add(disco);
            }

            for (int i = 0; i < e.ArtistasID.Count(); i++)
            {
                string user = e.ArtistasID[i];
                var artistas = db.Artista.Where(x => x.Usuario1.Nick == user).FirstOrDefault();
                at.Add(artistas);
            }
            Trace.TraceInformation(":::::::::::::::TODO BIEN:::::::::::::::");

            for (int i = 0; i < e.LocalId.Count(); i++)
            {
                string user = e.LocalId[i];
                var artistas = db.Artista.Where(x => x.Usuario1.Nick == user).FirstOrDefault();
                local.Add(artistas);
                Trace.TraceInformation(":::::::::::::::TODO BIEN:::::::::::::::"+i);

            }

            Explora exp = new Explora(k, dk, at, local);
            return View(exp);
        }
    }
}

Spot It Free/Proyecto Spot-it Free/Views/Artistas/Create.cshtml
@model Proyecto_Spot_it_Free.Artista

@{
    ViewBag.Title = "Crear Artista";
}

<h2>Crear Artista</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Usuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_artista, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_artista, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_artista, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>   
    @Html.ActionLink("Volver", "Index", "Explora")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Spot It Free/Proyecto Spot-it Free/Views/Artistas/Delete.cshtml
@model Proyecto_Spot_it_Free.Artista

@{
    ViewBag.Title = "Borrar Artistas";
}
<style>
    body {
        color: #ffffff;
    }
</style>
<body>
    <h2>Borrar Artista</h2>

    <h3>¿Estás seguro de que quieres borrar este artista?</h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre_artista)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre_artista)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Usuario1.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Usuario1.Nombre)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            <a href="@Url.Action("Details", "Discos", new { id = Model.Disco1.Id})">Volver</a>
        </div>
        }
    </div>
</body>

Spot It Free/Proyecto Spot-it Free/Views/Artistas/Details.cshtml
@model Proyecto_Spot_it_Free.Artista
<br /><br />
@{
    ViewBag.Title = "Detalles de Artistas";
    Usuario user = (Usuario)Session["Usuario"];
    if (user == null)
    {
        Response.Redirect("~/Principal/Principal");
    }
}

      <style>
                /*
          .thumbnail {
                 width: 240px;
                 height: 240px;
                 margin-bottom: 50px;
                 margin-right:50px;
                 align-items:center;
                 border:none;
             }


             .image {
                 width: 100%;
                 height: 100%;

              }

                 .image img {
                     -webkit-transition: all 1s ease;  Safari and Chrome
             -moz-transition: all 1s ease;
             -ms-transition: all 1s ease;
             -o-transition: all 1s ease;
             transition: all 1s ease;
             }

             .image :hover img {
                 -webkit-transform: scale(1.04);
                 -moz-transform: scale(1.04);
                 -ms-transform: scale(1.04);
                 -o-transform: scale(1.04);
                 transform: scale(1.04);
             }

             .img__description:hover {
                 visibility: visible;
                 opacity: 1;
             }

             .img__description {
                 position: absolute;
                 top: 0;
                 bottom: 0;
                 left: 0;
                 right: 0;
                 background: rgba(29, 106, 154, 0.72);
                 color: #fff;
                 visibility: hidden;
                 opacity: 0;
                 /* transition effect. not necessary
                 transition: opacity .2s, visibility .2s;
             }

             #oo:hover {
                 visibility: visible;
                 opacity: 1;
             }


             */



                * {
                    margin: 0;
                    padding: 0;
                    border: 0;
                    border: none;
                }

                /* relevant styles */
                .img__wrap {
                    position: relative;
                    height: 280px;
                    width: 280px;
                    top: -10px;
                }

          .img__description {
              position: absolute;
              margin-top:0px;
              top: 0;
              bottom: 0;
              left: 0;
              right: 0;
              background-color: #464545;
              color: #fff;
              visibility: hidden;
              opacity: 0;
              width: 280px;
              height: 280px;;
              /* transition effect. not necessary */
              transition: opacity .2s, visibility .2s;
              border: none;
          }

                .img__wrap:hover .img__description {
                    visibility: visible;
                    opacity: 1;
                    border: none;
                }

                .img__wrap:hover {
                }

                 body {
                    color: #ffffff;
                }
          img {
              border-radius: 30px 30px 30px 30px;
              -moz-border-radius: 30px 30px 30px 30px;
              -webkit-border-radius: 30px 30px 30px 30px;
              border: 0px solid #000000;
          }
     
</style>
      <body>
          <h2 style="text-align:center">@Model.Nombre_artista</h2>

          <div>
              <hr />
              <p style="text-align:center;"><img style="box-shadow: 2px 2px 1px grey;" src="~/Images/@Model.Usuario1.Imagen" width="300" height="300" /></p>
              <p style="text-align:center">@Model.Usuario1.Localidad , @Model.Usuario1.Pais</p>
              <div style="text-align:center"><a class="btn btn-default" style="align-self:center" href="mailto:@Model.Usuario1.Mail?Subject=Hola%20,te%20he%20descubierto%20en%20Spot%20It%20Free" target="_top"><button>Contacta con @Model.Nombre_artista</button></a></div>
              <hr />
          </div>
          <h1 style="text-align:center">Discos del artista</h1>
          @{
        if (user.Nick == Model.Usuario1.Nick)
        {
          <p><a href="~/Discos/Create?nickusuario=@Model.Usuario1.Nick"> Añadir un nuevo disco </a></p>
}

          }
          <hr />
          <div style="margin-left:-40px">
              @foreach (var item in Model.Disco)
        {
          <a href="@Url.Action("Details", "Discos", new { id = item.Id})">
              <div class="thumbnail" style="display:inline-block;border:none;background-color:#3E3D3D;">
                  <div class="img__wrap">
                      <img class="img__img" src="~/Portadas/@item.Imagen" width="280 px" height="280 px" style="margin-bottom:100px" />
                      <h3 style=" border-radius: 30px 30px 30px 30px;-moz-border-radius: 30px 30px 30px 30px;
                        -webkit-border-radius: 30px 30px 30px 30px; border: 0px solid #000000; font-weight:150;
                        -webkit-text-stroke: 0.8px black;" class="img__description">
                          • @item.Nombre<hr />
                          Canciones en el disco: @item.Cancion.Count()
                      </h3>
                  </div>
              </div>
          </a>
}

          </div>


          <p>

          </p>


      </body>

Spot It Free/Proyecto Spot-it Free/Views/Artistas/Edit.cshtml
@model Proyecto_Spot_it_Free.Artista

@{
    ViewBag.Title = "Editar Artistas";
    Usuario user = (Usuario)Session["Usuario"];
}

<style>
    body {
        color: #ffffff;
    }
</style>
<body>
    <h2>Editar Artista</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Usuario)

            <div class="form-group">
                @Html.LabelFor(model => model.Nombre_artista, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre_artista, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre_artista, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar cambios" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Volver", "Index", "Explora")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>

Spot It Free/Proyecto Spot-it Free/Views/Artistas/Index.cshtml
@model IEnumerable<Proyecto_Spot_it_Free.Artista>


@{
  ViewBag.Title = "Index";
  Usuario user = (Usuario)Session["Usuario"];
}
<br /><br />
      <style>
          body {
              color: #ffffff;
          }
      </style>
      <body>
          <h2>Artistas de Spot-It Free</h2>

          <p>
              ¿Eres Artista?
              @Html.ActionLink("Crea un nuevo artista", "Create")
          </p>
          <table class="table">
              <tr>
                  <th>
                      @Html.DisplayNameFor(model => model.Nombre_artista)
                  </th>
                  <th>
                      @Html.DisplayNameFor(model => model.Usuario1.Nombre)
                  </th>
                  <th></th>
              </tr>

              @foreach (var item in Model)
        {
          <tr>
              <td>
                  @Html.DisplayFor(modelItem => item.Nombre_artista)
              </td>
              <td>
                  @Html.DisplayFor(modelItem => item.Usuario1.Nombre)
              </td>
              @if (user.Tipo == 1)
        {
          <td>
              @Html.ActionLink("Editar", "Edit", new { id = item.Usuario }) |
              @Html.ActionLink("Detalles", "Details", new { id = item.Usuario }) |
              @Html.ActionLink("Borrar", "Delete", new { id = item.Usuario })
          </td>
}
              @if (user.Tipo != 1)
        {
          <td>
              @Html.ActionLink("Detalles", "Details", new { id = item.Usuario })
          </td>
}
          </tr>
}

          </table>
      </body>