Spot It Free/Proyecto Spot-it Free/Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class ArtistasController : Controller
    {
        private espotiEntities db = new espotiEntities();

        // GET: Artistas
        public async Task<ActionResult> Index()
        {
            
            var artista = db.Artista.Include(a => a.Usuario1);
            return View(await artista.ToListAsync());
        }

        // GET: Artistas/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // GET: Artistas/Create
        public ActionResult Create()
        {
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre");
            return View();
        }

        // POST: Artistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Usuario,Nombre_artista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Artista.Add(artista);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // GET: Artistas/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // POST: Artistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Usuario,Nombre_artista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artista).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // GET: Artistas/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Artista artista = await db.Artista.FindAsync(id);

            List<Disco> c = new List<Disco>();
            c = artista.Disco.ToList<Disco>();

            for (int i = 0; i < c.Count; i++)
            {
                db.Disco.Remove(c[i]);
                await db.SaveChangesAsync();
            }

            db.Artista.Remove(artista);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Spot It Free/Proyecto Spot-it Free/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class LoginController : Controller
    {
        private espotiEntities db = new espotiEntities();

        public string nick { get; set; }
        public string pass { get; set; }
        public object ErrorMessage { get; private set; }
        string error = "";

        // GET: Login
        public ActionResult Login()
            {
              return View();
            }

        [HttpPost]
        public ActionResult Login(Usuario user)
        {
            var obj = db.Usuario.FirstOrDefault(a => a.Nick == user.Nick && a.Pass == user.Pass);
            if (obj == null)
            {
                obj = db.Usuario.FirstOrDefault(a => a.Mail == user.Nick && a.Pass == user.Pass);
                if (obj == null)
                {
                    return RedirectToAction("Principal","Principal");
                }
            }
            Session["Usuario"] = obj;
            if (obj.Validado == 0)
            {
                return RedirectToAction("Index", "Validacion");
            }
                return RedirectToAction("UserDashBoard");            
        }

        public ActionResult UserDashBoard()
        {
            return View();
            /*      
              if (Session["Nick"] != null)
              {
                return View();
              }
              else
              {
                return RedirectToAction("Login");
              }*/
        }

        public ActionResult CerrarSesion()
        {
          return View();
        }

        public ActionResult Perfil()
        {
          return View();
        }
  }
}

Spot It Free/Proyecto Spot-it Free/Controllers/RestauraController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class RestauraController : Controller
    {
        // GET: Restaura
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Restaura(string apodoartista) {
            int nuevapass = generapass();
            CambiaPass(apodoartista, nuevapass);
             return RedirectToAction("Principal", "Principal");
        }
        public void CambiaPass(string mail,int pass){
            string query = "update usuario set Pass = '"+pass+"' where mail = '"+mail+"'";
            string cadena = System.Configuration.ConfigurationManager.ConnectionStrings["cadena1"].ConnectionString;
            SqlConnection conexion = new SqlConnection(cadena);
            conexion.Open();
            SqlCommand comando = new SqlCommand(query, conexion);
            comando.ExecuteNonQuery();
            conexion.Close();
            enviaEmail(mail, pass);
        }
        public void enviaEmail(string email,int pass)
        {
            string mailBodyhtml = "";
            if (email.Length > 0) { 
            var msg = new MailMessage("spotitfree@gmail.com", email, "Se ha generado una nueva contraseña: ", mailBodyhtml);
            //   msg.To.Add(email);
            msg.IsBodyHtml = true;
            msg.Body = "Tu nueva contraseña es: " + pass + "";
            var smtpClient = new SmtpClient("smtp.gmail.com", 587); //if your from email address is "from@hotmail.com" then host should be "smtp.hotmail.com"**
            smtpClient.UseDefaultCredentials = true;
            smtpClient.Credentials = new NetworkCredential("spotitfree@gmail.com", "spotitfree.net");
            smtpClient.EnableSsl = true;
            smtpClient.Send(msg);
            }
         }

        public int generapass() {
            Random r = new Random();
            int pass = r.Next(11111111, 999999999);
            return pass;
        }
    }
}

Spot It Free/Proyecto Spot-it Free/Views/Login/CerrarSesion.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
  ViewBag.Title = "Cerrar Sesión";
}

<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
<link rel="stylesheet" href="~/Content/Style1.css">
<link rel="stylesheet" href="~/Content/bootstrap.css">
<link rel="stylesheet" href="~/Content/bootstrap.min.css">

<br /><br /><br /><br />
<html>
<body>
    <fieldset>
        <legend>Cerrar Sesión</legend>
        @using (Html.BeginForm())
        {   
            Usuario user = (Usuario)Session["Usuario"];
            <h4 align="center">@user.Nick has cerrado la sesión </h4>
            Session.Clear();
            <h4 align="center">@Html.ActionLink("Volver a Spot-It Free", "Principal", "Principal")</h4>
        }
        
    </fieldset>
</body>

</html>
<br />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Spot It Free/Proyecto Spot-it Free/Views/Login/Login.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
  ViewBag.Title = "Principal";
}

<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
<link rel="stylesheet" href="~/Content/Style1.css">
<link rel="stylesheet" href="~/Content/bootstrap.css">
<link rel="stylesheet" href="~/Content/bootstrap.min.css">

<html>
<body>
    <center>

        <h1 align="center">Novedades de Spot-It Free</h1>

        @using (Html.BeginForm("Login", "Login", FormMethod.Post))
        {
        <fieldset>


            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @if (@ViewBag.Message != null)
            {
            <div style="border: 1px solid red">
                @ViewBag.Message
            </div>
            }

            <br />
            @* Holaaaaaaaaa *@
            @using (Html.BeginForm())
            {
                Usuario user = (Usuario)Session["Usuario"];

                if (user == null)
                {

                <div class="login-wrap-2">
                    <div class="login-html">
                        <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-2" class="tab"></label>
                        <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-1" class="tab">Inicio de Sesión</label>

                        <div class="login-form">
                            <div class="sign-in-htm">

                                <div class="group">
                                    @Html.LabelFor(a => a.Nick)
                                    @Html.TextBoxFor(a => a.Nick)
                                    @Html.ValidationMessageFor(a => a.Nick)
                                </div>

                                <div class="group">

                                    @Html.LabelFor(a => a.Pass)
                                    @Html.PasswordFor(a => a.Pass)
                                    @Html.ValidationMessageFor(a => a.Pass)
                                    <h3 align="center">Usuario/Password incorrectos</h3>
                                </div>

                                <input type="submit" value="Login" />

                                <br />
                                <div class="hr"></div>
                                <br />

                                <div class="foot-lnk">
                                    <a  href="@Url.Action("Index","Restaura")"> ¿Has olvidado tu contraseña?</a> 
                                </div>
                                <h3 align="center"><a href="~/Usuarios/Create"> Regístrate</a></h3>


                            </div>
                        </div>
                    </div>
                </div>
                }
                else
                {
                }
            }
        </fieldset>
        }

    </center>
    <br />
    <br />
</body>
</html>

Spot It Free/Proyecto Spot-it Free/Views/Login/Perfil.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
  ViewBag.Title = "Perfil";
  Usuario user = (Usuario)Session["Usuario"];
  Artista art = (Artista)Session["Artista"];
}

<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
<link rel="stylesheet" href="~/Content/Style1.css">
<link rel="stylesheet" href="~/Content/bootstrap.css">
<link rel="stylesheet" href="~/Content/bootstrap.min.css">

<br /><br />
<html>
    <body>
        <fieldset>
            @using (Html.BeginForm())
            {
                <h2 align="center">Perfil de @user.Nick</h2>
                <br />
                <hr />

                <div class="row">
                    <div class="col-md-3">
                        <div class="col-md-12" align="center">
                            <img class="img-responsive img-portfolio img-hover" src="~/Images/@user.Imagen" />
                        </div>
                        <div class="col-md-12">
                            <p class="text-center"><strong>Imagen de @user.Nick</strong></p>
                        </div>
                    </div>
                </div>
                
            }
        </fieldset>
    </body>

</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Spot It Free/Proyecto Spot-it Free/Views/Login/UserDashBoard.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
    ViewBag.Title = "UserDashBoard";
}

<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
<link rel="stylesheet" href="~/Content/Style1.css">
<link rel="stylesheet" href="~/Content/bootstrap.css">
<link rel="stylesheet" href="~/Content/bootstrap.min.css">
<style>
    html, body {
        height: 100%;
        background-color: #464545;
        color: #ffffff;
    }

    .center {
        margin: auto;
        position: relative;
        text-align: center;
        top: 50%;
        width: 20%;
    }
</style>
<br /><br />
<html>
<body>
    <fieldset>

        @using (Html.BeginForm())
        {
            Usuario user = (Usuario)Session["Usuario"];

            if (user != null)
            {
                <h3 align="center">Bienvenido a Spot-It Free @user.Nombre</h3>
                <div style="width:400px" class="center">
                    <a href="~/Explora/Index"><h3> ¿Descubrimos nueva música? </h3></a>
                </div>
                try
                {
                    if (user.Artista.Nombre_artista != null)
                    {
                        <div style="width:400px" class="center">
                            <h3> o...</h3>
                            <a href="@Url.Action("Details","Artistas", new {id=user.Nick})"><h3> ¿Nos descubres tu música? </h3></a>
                        </div>
                    }
                }
                catch (Exception e) { }
            }

            else
            {
                Response.Redirect("~/Principal/Principal");
            }

        }

    </fieldset>

</body>

</html>