Spot It Free/Proyecto Spot-it Free/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class PrincipalController : Controller
    {
        // GET: Principal
        public ActionResult Principal()
        {
            return View();
        }
    }
}

Spot It Free/Proyecto Spot-it Free/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free;
using System.Net.Mail;
using Renci.SshNet;
using System.IO;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Data.SqlClient;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class UsuariosController : Controller
    {
        private espotiEntities db = new espotiEntities();
        
        // GET: Usuarios
        public async Task<ActionResult> Index()
        {
            var usuario = db.Usuario.Include(u => u.Artista).Include(u => u.Genero);
            return View(await usuario.ToListAsync());
        }

        public ActionResult convertirImagen(string mail)
        {
          var imagen = db.Usuario.Where(x => x.Mail == mail).FirstOrDefault();
          return File(imagen.Imagen, "image/jpeg");
        }

        // GET: Usuarios/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = await db.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            ViewBag.Nick = new SelectList(db.Artista, "Usuario", "Nombre_artista");
            ViewBag.Generofav = new SelectList(db.Genero, "Nombre", "Descripcion");
            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Nombre,Apellidos,Mail,Pass,Nick,Generofav,Localidad,Pais,Direccion,Tipo,Telefono,Imagen,Codigo_validacion,Validado")] Usuario usuario, HttpPostedFileBase ImagenUsuario, string apodoartista)
        {
            //Genera un random de 4 numeros
            Random r = new Random();
            int codigo = r.Next(1000,9999);
            int validado = 0;
            bool esArtista = false;
            string apododeartista = "";
            if (apodoartista != string.Empty) {
                apododeartista = apodoartista;
                esArtista = true;
            }
            /**
             *Transforma el archivo HTTPPOSTED FILE en una imagen que podemos manejar  
             */

            if (ImagenUsuario != null)
            {
                string filename = Path.GetFileNameWithoutExtension(ImagenUsuario.FileName); //Obitene el nombre sin extension
                string extension = Path.GetExtension(ImagenUsuario.FileName);
                filename = usuario.Nick + extension;
                usuario.Imagen = filename; // Este será el nombre que guardamos en la BDD 
                filename = Path.Combine(Server.MapPath("~/Images/"), filename);
                ImagenUsuario.SaveAs(filename);
               // subeArchivoSFTP(filename);
            }
            else {
                usuario.Imagen = "default.png";
            }

            if (ModelState.IsValid)
            {
                if (esArtista == null)
                {
                    usuario.Tipo = 0;
                }
                else
                {
                    usuario.Tipo = 0;
                    esArtista = true;
                }
                
                usuario.Codigo_validacion = codigo.ToString();
                usuario.Validado = validado;
                enviaEmail(usuario.Mail, usuario.Nombre, usuario.Codigo_validacion);          

                try
                {
                    db.Usuario.Add(usuario);
                    await db.SaveChangesAsync();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Trace.TraceInformation("*****************0000000:::::Property: {0} Error: {1}",
                                validationError.PropertyName,
                                validationError.ErrorMessage);
                        }
                    }
                }

                if (esArtista == true) {
                    insertaArtista(apododeartista, usuario.Nick);
                }
            }
            var obj = db.Usuario.FirstOrDefault(a => a.Nick == usuario.Nick && a.Pass == usuario.Pass);
            Session["Usuario"] = obj;
            ViewBag.Nick = new SelectList(db.Artista, "Usuario", "Nombre_artista", usuario.Nick);
            ViewBag.Generofav = new SelectList(db.Genero, "Nombre", "Descripcion", usuario.Generofav);
            return RedirectToAction("Index", "Validacion"); 
        }
        public void insertaArtista(string apodo,string usuario) {
            string cadena = System.Configuration.ConfigurationManager.ConnectionStrings["cadena1"].ConnectionString;
            SqlConnection conexion = new SqlConnection(cadena);
            conexion.Open();
            SqlCommand comando = new SqlCommand("insert into Artista(usuario,Nombre_artista) values('"+usuario+"','"+apodo+"')", conexion);
            comando.ExecuteNonQuery();
            conexion.Close();
        }
        public bool subeArchivoSFTP(string url) {
            bool subida = false;
            const string host = "direcciondelhost";
            const string username = "usuariodelhost";
            const string password = "passdelhost";
            const string workingdirectory = "directoriodelhost";
            string uploadfile = url;
            using (var client = new SftpClient(host, 22, username, password))
            {
                client.Connect();
                client.ChangeDirectory(workingdirectory);
                var listDirectory = client.ListDirectory(workingdirectory);
                using (var fileStream = new FileStream(uploadfile, FileMode.Open))
                {
                    client.BufferSize = 4 * 1024; // bypass Payload error large files
                    client.UploadFile(fileStream, Path.GetFileName(uploadfile));
                    subida = true;
                }
            }
            return subida;
        }


        public static Bitmap ResizeImage(Image image, int width, int height)
        {
            var destRect = new Rectangle(0, 0, width, height);
            var destImage = new Bitmap(width, height);

            destImage.SetResolution(image.HorizontalResolution, image.VerticalResolution);

            using (var graphics = Graphics.FromImage(destImage))
            {
                graphics.CompositingMode = CompositingMode.SourceCopy;
                graphics.CompositingQuality = CompositingQuality.HighQuality;
                graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                graphics.SmoothingMode = SmoothingMode.HighQuality;
                graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;

                using (var wrapMode = new ImageAttributes())
                {
                    wrapMode.SetWrapMode(WrapMode.TileFlipXY);
                    graphics.DrawImage(image, destRect, 0, 0, image.Width, image.Height, GraphicsUnit.Pixel, wrapMode);
                }
            }
            return destImage;
        }


        public void enviaEmail(string email, string nombre, string codigo) {
            string mailBodyhtml = "";
            var msg = new MailMessage("spotitfree@gmail.com", email, "Codigo de confirmacion: ", mailBodyhtml);
         //   msg.To.Add(email);
            msg.IsBodyHtml = true;
            msg.Body = "Hola " + nombre + ", tu codigo de confirmacion es: " + codigo + "";

            var smtpClient = new SmtpClient("smtp.gmail.com", 587); //if your from email address is "from@hotmail.com" then host should be "smtp.hotmail.com"**
            smtpClient.UseDefaultCredentials = true;
            smtpClient.Credentials = new NetworkCredential("spotitfree@gmail.com", "spotitfree.net");
            smtpClient.EnableSsl = true;
            smtpClient.Send(msg);
            Console.WriteLine("Email Sended Successfully");
        }

        // GET: Usuarios/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = await db.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.Nick = new SelectList(db.Artista, "Usuario", "Nombre_artista", usuario.Nick);
            ViewBag.Generofav = new SelectList(db.Genero, "Nombre", "Descripcion", usuario.Generofav);
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Nombre,Apellidos,Mail,Pass,Nick,Generofav,Localidad,Pais,Direccion,Tipo,Telefono,Imagen,Codigo_validacion,Validado")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {

Spot It Free/Proyecto Spot-it Free/Views/Usuarios/Create.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
    ViewBag.Title = "Nuevo Usuario";
}
<style>
    input[type='checkbox'] {
        zoom: 1.5;
        transform: scale(1.5);
        -ms-transform: scale(1.5);
        -webkit-transform: scale(1.5);
        -o-transform: scale(1.5);
        -moz-transform: scale(1.5);
        transform-origin: 0 0;
        -ms-transform-origin: 0 0;
        -webkit-transform-origin: 0 0;
        -o-transform-origin: 0 0;
        -moz-transform-origin: 0 0;
        -webkit-transform-origin: 0 0;
    }

        input[type='checkbox']:checked {
            background: #abd;
        }
    #myCheck:checked + #area {
        display: block !important;
    }

   body {
        background-color: #464545;
        color: #ffffff;
    }
    label {
        color: #ffffff;
    }
    .control-label {
        color: #ffffff;
    }
    p {
        color: #ffffff;
    }

</style>

<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
<link rel="stylesheet" href="~/Content/Style1.css">
<link rel="stylesheet" href="~/Content/bootstrap.css">
<link rel="stylesheet" href="~/Content/bootstrap.min.css">



    @using (Html.BeginForm("Create", "Usuarios", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <hr />
        <center>
            <div class="login-wrap1">
                <div class="login-html">
                    <input id="tab-1" type="radio" name="tab" class="sign-up" checked><label for="tab-1" class="tab">¡Registrate ya!</label>

                    <div class="login-form">

                        <div class="sign-up-htm">
                            <br />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="password" name="Pass" class="form-control">
                                    @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Nick, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Nick, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Nick, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Localidad, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Localidad, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Localidad, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />


                            <div class="form-group">
                                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="ImagenUsuario" />
                                    @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                                </div>
                            </div><br /><br />

                            <div class="form-group">
                                <p class="control-label col-md-2">¿Artista?</p>
                                <p style="text-align:left; margin-left:130px">
                                    <input style="margin-top:-20px" id="myCheck" onclick="addbox();" name="VisibleC" type="checkbox" />
                                </p>
                            </div><br /><br />

                            <script type="text/javascript">
                                function addbox() {
                                    if (document.getElementById('myCheck').checked) {
                                        document.getElementById('area').style.display = 'block';
                                    } else {
                                        document.getElementById('area').style.display = 'none';
                                    }
                                }
                            </script>
                            <div class="row" id="area" style="display: none;">
                                <div class="form-group" style="margin-top:-30px">
                                    <p class="control-label col-md-2" style="margin-left:18px">Apodo:</p>
                                    <div class="col-md-10">
                                        <input type="text" name="apodoartista" style="width:620px; margin-left:128px; margin-top:-38px" class="form-control text-box single-line" />

                                    </div>
                                </div><br /><br />
                            </div>

                            <br /><br />
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-8">
                                    <input style="margin-top:-35px" type="submit" value="Crear nuevo usuario" class="btn btn-default" />
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </center>
    }
    <br />
    <br /><br /><br />
    <div class="col-md-12">
        <h5 align="center">@Html.ActionLink("Volver al inicio de sesión", "Principal", "Principal")</h5>
    </div>
    <br />
    <br />
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Spot It Free/Proyecto Spot-it Free/Views/Usuarios/Delete.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
    ViewBag.Title = "Borrar Usuario";
}
<style>
    body {
        background-color: #464545;
        color: #ffffff;
    }
</style>
<body>
    <h2>Borrar Usuario</h2>

    <h3>¿Estás seguro de que quieres borrar este usuario?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Apellidos)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Apellidos)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Mail)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Mail)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Pass)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Pass)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Localidad)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Localidad)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Pais)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Pais)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Direccion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tipo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tipo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Telefono)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telefono)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Imagen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Imagen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Codigo_validacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Codigo_validacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Validado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Validado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Artista.Nombre_artista)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Artista.Nombre_artista)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Genero.Descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Genero.Descripcion)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Borrar" class="btn btn-default" /> |
                @Html.ActionLink("Volver", "Index")
            </div>
        }
    </div>
</body>

Spot It Free/Proyecto Spot-it Free/Views/Usuarios/Details.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
    ViewBag.Title = "Detalles de Usuario";
}

<style>
    body {
        background-color: #464545;
        color: #ffffff;
    }

    <style > html, body {
        height: 100%;
    }

    #tableContainer-1 {
        height: 100%;
        width: 100%;
        display: table;
    }

    #tableContainer-2 {
        vertical-align: middle;
        display: table-cell;
        height: 100%;
    }

    #myTable {
        margin: 0 auto;
    }
</style>
<body>
    <h2 style="text-align:center">Detalles de @Model.Nick</h2>
    <hr />
    <p style=" text-align:center"> <img style="width:280px; height:280px" src="~/Images/@Model.Imagen" /></p>
    
    <p style=" text-align:center">Nombre: @Model.Nombre</p>
    <p style=" text-align:center">Apellidos: @Model.Apellidos</p>
    <p style=" text-align:center">Email: @Model.Mail</p>
    <p style=" text-align:center">Localidad: @Model.Localidad</p>
    <p style=" text-align:center">Direccion: @Model.Direccion</p>
    <p style=" text-align:center">Pais: @Model.Pais</p>




    <p>
        @Html.ActionLink("Edita tu perfil", "Edit", new { id = Model.Nick })
    </p>
</body>

Spot It Free/Proyecto Spot-it Free/Views/Usuarios/Edit.cshtml
@model Proyecto_Spot_it_Free.Usuario

@{
    ViewBag.Title = "Editar Usuario";
}
<style>
    body {
        background-color: #464545;
        color: #ffffff;
    }
</style>
<body>
    <h2>Editar Usuario</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
                </div>
            </div>
 
            <div class="form-group">
                @Html.LabelFor(model => model.Localidad, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Localidad, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Localidad, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                </div>
            </div>

          

            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                </div>
            </div>

   
 
 

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar cambios" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

        <div>
             <a href="~/Login/UserDashBoard">Volver</a>

        </div>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}