Spot It Free/Proyecto Spot-it Free/Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class ArtistasController : Controller
    {
        private espotiEntities db = new espotiEntities();

        // GET: Artistas
        public async Task<ActionResult> Index()
        {
            
            var artista = db.Artista.Include(a => a.Usuario1);
            return View(await artista.ToListAsync());
        }

        // GET: Artistas/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // GET: Artistas/Create
        public ActionResult Create()
        {
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre");
            return View();
        }

        // POST: Artistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Usuario,Nombre_artista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Artista.Add(artista);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // GET: Artistas/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // POST: Artistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Usuario,Nombre_artista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artista).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Usuario = new SelectList(db.Usuario, "Nick", "Nombre", artista.Usuario);
            return View(artista);
        }

        // GET: Artistas/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = await db.Artista.FindAsync(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Artista artista = await db.Artista.FindAsync(id);

            List<Disco> c = new List<Disco>();
            c = artista.Disco.ToList<Disco>();

            for (int i = 0; i < c.Count; i++)
            {
                db.Disco.Remove(c[i]);
                await db.SaveChangesAsync();
            }

            db.Artista.Remove(artista);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Spot It Free/Proyecto Spot-it Free/Controllers/BusquedaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free.Models;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class BusquedaController : Controller
    {
        private espotiEntities db = new espotiEntities();

        // GET: Busqueda
        public ActionResult Index(string SearchText)
        {
            Busqueda e = new Busqueda(SearchText);
            List<Cancion> k = new List<Cancion>();
            List<Disco> dk = new List<Disco>();
            List<Artista> at = new List<Artista>();
            List<Artista> local = new List<Artista>();




            //Esto es un comentario
            /* 
             * Esto tambien, no se ejecuta
             */

            for (int i = 0; i < e.CancionesID.Count(); i++)
            {
                int id = e.CancionesID[i];
                Cancion cs = db.Cancion.Where(x => x.Id == id).SingleOrDefault(); 
                k.Add(cs);
            }
            for (int i = 0; i < e.DiscosID.Count(); i++)
            {
                int id = e.DiscosID[i];
                var disco = db.Disco.Where(x => x.Id == id).FirstOrDefault();
                dk.Add(disco);
            }

            for (int i = 0; i < e.ArtistasID.Count(); i++)
            {
                string user = e.ArtistasID[i];
                var artistas = db.Artista.Where(x => x.Usuario1.Nick == user).FirstOrDefault();
                at.Add(artistas);
            }

            for (int i = 0; i < e.LocalesID.Count(); i++)
            {
                string user = e.LocalesID[i];
                var artistasLocales = db.Artista.Where(x => x.Usuario1.Nick == user).FirstOrDefault();
                local.Add(artistasLocales);
            }

            Busqueda BBB = new Busqueda(k, dk, at,local);
            return View(BBB);
        }



    }
}

Spot It Free/Proyecto Spot-it Free/Controllers/CancionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free;
using System.IO;
using System.Data.SqlClient;
using Renci.SshNet;
using System.Diagnostics;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class CancionesController : Controller
    {
        private espotiEntities db = new espotiEntities();
        private int idDelDisco = -1;

        // GET: Canciones
        public async Task<ActionResult> Index()
        {
            var cancion = db.Cancion.Include(c => c.Disco1).Include(c => c.Genero1);
            return View(await cancion.ToListAsync());
        }

        // GET: Canciones/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cancion cancion = await db.Cancion.FindAsync(id);
            if (cancion == null)
            {
                return HttpNotFound();
            }
            return View(cancion);
        }

        /* GET: Canciones/Create
        public ActionResult Create()
        {
            ViewBag.Disco = new SelectList(db.Disco, "Id", "Nombre");
            ViewBag.Genero = new SelectList(db.Genero, "Nombre", "Descripcion");
            return View();
        }*/
        public ActionResult Create(int iddisco)
        {
            int id = iddisco;
            this.idDelDisco = iddisco;
            ViewBag.Disco= db.Disco.Where(x => x.Id == iddisco).FirstOrDefault();
          
            ViewBag.Disco = new SelectList(db.Disco.Where(x => x.Id == iddisco), "Id", "Nombre");
            ViewBag.Genero = new SelectList(db.Genero, "Nombre", "Descripcion");
            return View();
        }

        public ActionResult SumaRepro(int cancion) {
            string cadena = System.Configuration.ConfigurationManager.ConnectionStrings["espotiEntities"].ConnectionString;
            SqlConnection conexion = new SqlConnection(cadena);
            conexion.Open();
            SqlCommand comando = new SqlCommand("update Cancion set  Reproducciones=Reproducciones +1 where id ="+cancion+"", conexion);
            comando.ExecuteNonQuery();
            conexion.Close();
            return View();
        }

        // POST: Canciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Titulo,Valoracion,Votos,Reproducciones,Genero,Disco,Visible,ubi")] Cancion cancion, HttpPostedFileBase FileAudio, bool? VisibleC)
        {
            int ide = devuelveid();

            if (ModelState.IsValid)
            {

                /**
                 *Transforma el archivo HTTPPOSTED FILE en un archivo que podemos manejar  
                 */
                if (FileAudio != null)
               {
                    if (VisibleC == null)
                    {
                        cancion.Visible = 0;
                    }
                    else
                    {
                        cancion.Visible = 1;
                    }
                    string filename = Path.GetFileNameWithoutExtension(FileAudio.FileName); //Obitene el nombre sin extension
                    string extension = Path.GetExtension(FileAudio.FileName);
                    filename = ide.ToString() + extension;
                    cancion.Valoracion = 0;
                    cancion.Votos = 0;
                    cancion.Reproducciones = 0;
               //     cancion.Disco =Disco;
                  
                    cancion.ubi= filename; // Este será el nombre que guardamos en la BDD 
                    filename = Path.Combine(Server.MapPath("~/Song/"), filename);
                    FileAudio.SaveAs(filename);
                    //subeArchivoSFTP(filename); 
                    db.Cancion.Add(cancion);
                    await db.SaveChangesAsync();
                }              
               
            }
            ViewBag.Disco = new SelectList(db.Disco, "Id", "Nombre", cancion.Disco);
            ViewBag.Genero = new SelectList(db.Genero, "Nombre", "Descripcion", cancion.Genero);
            return RedirectToAction("Details","Discos", new { id = devuelvedisco(ide)});
        }

        public bool subeArchivoSFTP(string url)
        {
            bool subida = false;
            const string host = "direcciondelhost";
            const string username = "usuariodelhost";
            const string password = "passdelhost";
            const string workingdirectory = "directoriodelhost";
            string uploadfile = url;
            using (var client = new SftpClient(host, 22, username, password))
            {
                client.Connect();
                client.ChangeDirectory(workingdirectory);
                var listDirectory = client.ListDirectory(workingdirectory);
                using (var fileStream = new FileStream(uploadfile, FileMode.Open))
                {
                    client.BufferSize = 4 * 1024; // bypass Payload error large files
                    client.UploadFile(fileStream, Path.GetFileName(uploadfile));
                    subida = true;
                }
            }
            return subida;
        }


        // GET: Canciones/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cancion cancion = await db.Cancion.FindAsync(id);
            if (cancion == null)
            {
                return HttpNotFound();
            }
            ViewBag.Disco = new SelectList(db.Disco, "Id", "Nombre", cancion.Disco);
            ViewBag.Genero = new SelectList(db.Genero, "Nombre", "Descripcion", cancion.Genero);
            return View(cancion);
        }
        public int devuelveid()
        {
            string query = "select max(Id) as id  from Cancion";
            int id = -1;
            string cadena = System.Configuration.ConfigurationManager.ConnectionStrings["cadena1"].ConnectionString;
            SqlConnection conexion = new SqlConnection(cadena);
            conexion.Open();
            SqlCommand comando = new SqlCommand(query, conexion);
            SqlDataReader registros = comando.ExecuteReader();

            while (registros.Read())
            {
                try
                {
                    id = Convert.ToInt32(registros["id"].ToString());
                }
                catch (Exception e) 
                {
                    id = 0;
                }
            }
            id++;
            conexion.Close();
            return id;        
        }

        public int devuelvedisco(int idx)
        {
            string query = "select disco as id from cancion where id="+idx+"";
            int id = -1;
            string cadena = System.Configuration.ConfigurationManager.ConnectionStrings["cadena1"].ConnectionString;
            SqlConnection conexion = new SqlConnection(cadena);
            conexion.Open();
            SqlCommand comando = new SqlCommand(query, conexion);
            SqlDataReader registros = comando.ExecuteReader();

            while (registros.Read())
            {
                try
                {
                    id = Convert.ToInt32(registros["id"].ToString());
                }
                catch (Exception e)
                {
                    id = 0;
                }
            }
            conexion.Close();
            return id;
        }


        // POST: Canciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Titulo,Valoracion,Votos,Reproducciones,Genero,Disco,Visible")] Cancion cancion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cancion).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Disco = new SelectList(db.Disco, "Id", "Nombre", cancion.Disco);
            ViewBag.Genero = new SelectList(db.Genero, "Nombre", "Descripcion", cancion.Genero);
            return RedirectToAction("Details", "Discos", new { id = devuelvedisco(devuelveid()) });
        }

        // GET: Canciones/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cancion cancion = await db.Cancion.FindAsync(id);
            if (cancion == null)
            {
                return HttpNotFound();
            }
            return View(cancion);
        }

        // POST: Canciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            int x = devuelvedisco(id);
            Cancion cancion = await db.Cancion.FindAsync(id);
            db.Cancion.Remove(cancion);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Discos", new { id = x });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

Spot It Free/Proyecto Spot-it Free/Views/Busqueda/Index.cshtml
@model Proyecto_Spot_it_Free.Models.Busqueda

@{
    ViewBag.Title = "Index";
}

<style>
    /*
    .thumbnail {
           width: 240px;
           height: 240px;
           margin-bottom: 50px;
           margin-right:50px;
           align-items:center;
           border:none;
       }


       .image {
           width: 100%;
           height: 100%;

        }

           .image img {
               -webkit-transition: all 1s ease;  Safari and Chrome
       -moz-transition: all 1s ease;
       -ms-transition: all 1s ease;
       -o-transition: all 1s ease;
       transition: all 1s ease;
       }

       .image :hover img {
           -webkit-transform: scale(1.04);
           -moz-transform: scale(1.04);
           -ms-transform: scale(1.04);
           -o-transform: scale(1.04);
           transform: scale(1.04);
       }

       .img__description:hover {
           visibility: visible;
           opacity: 1;
       }

       .img__description {
           position: absolute;
           top: 0;
           bottom: 0;
           left: 0;
           right: 0;
           background: rgba(29, 106, 154, 0.72);
           color: #fff;
           visibility: hidden;
           opacity: 0;
           /* transition effect. not necessary
           transition: opacity .2s, visibility .2s;
       }

       #oo:hover {
           visibility: visible;
           opacity: 1;
       }


       */



    * {
        margin: 0;
        padding: 0;
        border: 0;
        border: none;
    }

    /* relevant styles */
    .img__wrap {
        position: relative;
        height: 280px;
        width: 280px;
        top: -10px;
    }

    .img__description {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        background: none;
        color: #fff;
        visibility: hidden;
        opacity: 0;
        /* transition effect. not necessary */
        transition: opacity .2s, visibility .2s;
        border: none;
    }

    .img__wrap:hover .img__description {
        visibility: visible;
        opacity: 1;
        border: none;
    }

    .img__wrap:hover {
    }
</style>
<hr />
@if (Model.Locales.Count > 0)
{
    <h2 style="text-align:center; color:white">¡Artistas en tu zona!</h2>
    <hr />
    <div style="margin-left:-40px">

        @foreach (var item in Model.Locales)
        {
            <a href="@Url.Action("Details", "Artistas", new { id = item.Usuario1.Nick})">
                <div class="thumbnail" style="display:inline-block;border:none;background:none">
                    <div class="img__wrap">
                        <img class="img__img" src="~/Images/@item.Usuario1.Imagen" width="280 px" height="280 px" style="margin-bottom:100px" />

                    </div>
                </div>
            </a>
        }
    </div>

}
<h2 style="text-align:center;color:white">Canciones: </h2>
<hr />



<div style="margin-left:-40px">

    @foreach (var item in Model.Canciones)
    {
        <a href="@Url.Action("Details", "Canciones", new { id = item.Id})">
            <div class="thumbnail" style="display:inline-block;border:none; background:none">
                <div class="img__wrap">
                    <img class="img__img" src="~/Images/audiodefault.jpg" width="280 px" height="280 px" />
                    <p style="text-align:center">@item.Titulo by @item.Disco1.Artista1.Nombre_artista</p>
                </div>
            </div>
        </a>
    }
</div>

<hr />
<h2 style="text-align:center;color:white">Discos </h2>
<hr />

<div style="margin-left:-40px">

    @foreach (var item in Model.Discos)
    {
        <a href="@Url.Action("Details", "Discos", new { id = item.Id})">
            <div class="thumbnail" style="display:inline-block;border:none; background:none">
                <div class="img__wrap">
                    <img class="img__img" src="~/Portadas/@item.Imagen" width="280 px" height="280 px" style="margin-bottom:100px" />
                    <h3 style="  font-weight:150; -webkit-text-stroke: 0.8px black;" class="img__description">
                        • @item.Nombre<hr />
                        Canciones en el disco: @item.Cancion.Count()
                    </h3>
                </div>
            </div>
        </a>
    }
</div>
<hr />
<h2 style="text-align:center; color:white">Artistas </h2>
<hr />
<div style="margin-left:-40px">

    @foreach (var item in Model.Artistas)
    {
        <a href="@Url.Action("Details", "Artistas", new { id = item.Usuario1.Nick})">
            <div class="thumbnail" style="display:inline-block;border:none; background:none">
                <div class="img__wrap">
                    <img class="img__img" src="~/Images/@item.Usuario1.Imagen" width="280 px" height="280 px" style="" />
                    <h3 style="text-align:center">@item.Nombre_artista</h3>
                </div>
            </div>
        </a>
    }
</div>